theme: jekyll-theme-tactile
baseurl: /lrbs-scholarly-editing
title: Digital Scholarly Editing at the London Rare Books School !homepages 
description: Central repository for the 2018 Digital Scholarly Editing module at the Institute of English Studies
