theme: jekyll-theme-tactile
url: /lrbs-scholarly-editing
baseurl: ""
title: Digital Scholarly Editing at the LRBS 
description: Central repository for the 2018 Digital Scholarly Editing module at the London Rare Books School, Institute of English Studies

navbar-links:
  Outline: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
Home: "https://cmohge1.github.io/lrbs-scholarly-editing/"

author:
name: Christopher Ohge

url-pretty: "https://cmohge1.github.io/lrbs-scholarly-editing/"
