theme: jekyll-theme-slate
baseurl: /lrbs-scholarly-editing
title: Digital Scholarly Editing at the LRBS 
description: Central repository for the 2018 Digital Scholarly Editing module at the London Rare Books School, Institute of English Studies
